//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinglePage.Models.DomainModels.DTO.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
